### ISSUE TITLE
The method 'add' isn't defined for the class 'Function'.

### ISSUE THREAD

**Issue by kzawadi** [iampawan/FlutterLoginPageBloc#1]
i have run packages get but i keep having squick lines at .add(s)

`StreamBuilder<String>(
                stream: bloc.email,
                builder: (context, snapshot) => TextField(
                      onChanged: (s) => bloc.emailChanged.add(s),
                      keyboardType: TextInputType.emailAddress,
                      decoration: InputDecoration(
                          border: OutlineInputBorder(),
                          hintText: "Enter email",
                          labelText: "Email",
                          errorText: snapshot.error),
                    ),
              ),

**Comment by iampawan** [comment]
It is fixed

**Comment by kzawadi** [comment]
thanks ....have a nice day and hey i am learning a lot from your tutorials
